version: '3'
services:
    plex:
        image: plexinc/pms-docker
        container_name: plex
        restart: unless-stopped
        volumes:
            - /config/plex:/config
            - /media/movies:/data/movies
            - /media/series:/data/tvshows
            - /media/config/plex/transcode:/data/transcode
        networks:
            - local    
        restart: unless-stopped
        environment:
            - TZ=Asia/Karachi
            - PLEX_CLAIM=<claimToken>
            
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        restart: unless-stopped
        volumes:
            - /config/sonarr:/config
            - /media/downloads:/downloads
            - /media/series:/tv
        networks:
            - local    
        environment:
            - TZ=Asia/Karachi
        ports:
            - 8989:8989

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        restart: unless-stopped
        volumes:
            - /config/radarr:/config
            - /media/downloads:/downloads
            - /media/movies:/movies
        networks:
            - local        
        environment:
            - TZ=Asia/Karachi
        ports:
            - 7878:7878

    jackett:
        image: linuxserver/jackett
        container_name: jackett
        restart: unless-stopped
        volumes:
            - /config/jackett:/config
            - /media/downloads:/downloads
        networks:
            - local      
        environment:
            - TZ=Asia/Karachi
        ports:
            - 9117:9117

    transmission:
        image: linuxserver/transmission
        container_name: transmission
        restart: unless-stopped
        volumes:
            - /config/transmission:/config
            - /media/downloads:/downloads
        networks:
            - local    
        environment:
            - TZ=Asia/Karachi
        ports:
            - 9091:9091        
            - 51413:51413
            - "51413:51413/udp"

    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: unless-stopped
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/portainer/data:/data
        networks:
            - local    
        ports:
            - 9000:9000

networks:
  local:
    driver: bridge            
