version: '3'
services:
    plex:
        image: plexinc/pms-docker
        container_name: plex
        restart: unless-stopped
        volumes:
            - /config/plex:/config
            - /media:/data
            - /media/config/plex/transcode:/transcode
        network_mode: bridge  
        restart: unless-stopped
        environment:
            - TZ=Asia/Karachi
            - PLEX_CLAIM=<claimToken>
            - PLEX_UID=1000
            - PLEX_GID=1000
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp            
            
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        restart: unless-stopped
        volumes:
            - /config/sonarr:/config
            - /media/downloads:/downloads
            - /media/series:/tv
        network_mode: bridge
        environment:
            - TZ=Asia/Karachi
            - PGID=1000
            - PUID=1000            
        ports:
            - 8989:8989

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        restart: unless-stopped
        volumes:
            - /config/radarr:/config
            - /media/downloads:/downloads
            - /media/movies:/movies
        network_mode: bridge     
        environment:
            - TZ=Asia/Karachi
            - PGID=1000
            - PUID=1000            
        ports:
            - 7878:7878

    jackett:
        image: linuxserver/jackett
        container_name: jackett
        restart: unless-stopped
        volumes:
            - /config/jackett:/config
            - /media/downloads:/downloads
        network_mode: bridge
        environment:
            - TZ=Asia/Karachi
        ports:
            - 9117:9117

    transmission:
        image: linuxserver/transmission
        container_name: transmission
        restart: unless-stopped
        volumes:
            - /config/transmission:/config
            - /media/downloads:/downloads
        network_mode: bridge
        environment:
            - TZ=Asia/Karachi
            - PGID=1000
            - PUID=1000
        ports:
            - 9091:9091        
            - 51413:51413
            - "51413:51413/udp"

    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: unless-stopped
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/portainer/data:/data
        network_mode: bridge
        ports:
            - 9000:9000
